spring:
  application:
    name: search_service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    group-id: search_service

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost

    elasticsearch:
      port: 9200
      host: localhost
      indexes:
        users:
          title: "users"
          hours-rotation: 4
      index:
        auto-create: true
server:
  port: 8084

logging:
  level:
    root: info


